#!/bin/sh

set -e

uid=`getent passwd _bgpd | cut -d ":" -f 3`

if ! [ "$uid" ]; then
        adduser --quiet \
                --system \
                --disabled-password \
                --home /var/run \
                --no-create-home \
                --shell /sbin/nologin \
                --group \
		--force-badname \
                _bgpd
fi
